server:
  port: 8002
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/weolwo/cloud-config.git
          search-paths:
            - cloud-config
      label: master
#    zookeeper:
#      connect-string: localhost:2181
    nacos:
      discovery:
        server-addr: localhost:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'
