server:
  port: 9420
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: order_routh #\u8DEF\u7531\u7684ID\uFF0C\u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
          #uri: http://localhost:80   #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          uri: lb://cloud-order   #\u5339\u914D\u540E\u63D0\u4F9B\u670D\u52A1\u7684\u8DEF\u7531\u5730\u5740
          predicates:
            - Path=/order/**   #\u65AD\u8A00,\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531

        - id: payment_routh
          #uri: http://localhost:7001
          uri: lb://cloud-payment
          predicates:
            - Path=/payment/zookeeper  #\u65AD\u8A00,\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531
#    zookeeper:
#      connect-string: localhost:2181
    nacos:
        discovery:
          server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'