server:
  port: 80
spring:
  application:
    name: cloud-order
  cloud:
#    zookeeper:
#      connect-string: localhost:2181
    nacos:
      discovery:
        server-addr: localhost:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'